/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnim = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtabsen = new javax.swing.JTextField();
        txttugas = new javax.swing.JTextField();
        txtuts = new javax.swing.JTextField();
        txtuas = new javax.swing.JTextField();
        outnim = new javax.swing.JTextField();
        outnama = new javax.swing.JTextField();
        outakhir = new javax.swing.JTextField();
        outgrade = new javax.swing.JTextField();
        outket = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        btndownload = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnim.setBackground(new java.awt.Color(217, 217, 217));
        txtnim.setBorder(null);
        txtnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnimActionPerformed(evt);
            }
        });
        getContentPane().add(txtnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 260, 30));

        txtnama.setBackground(new java.awt.Color(217, 217, 217));
        txtnama.setBorder(null);
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 250, 30));

        txtabsen.setBackground(new java.awt.Color(217, 217, 217));
        txtabsen.setBorder(null);
        getContentPane().add(txtabsen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 250, 30));

        txttugas.setBackground(new java.awt.Color(217, 217, 217));
        txttugas.setBorder(null);
        txttugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttugasActionPerformed(evt);
            }
        });
        getContentPane().add(txttugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 250, 30));

        txtuts.setBackground(new java.awt.Color(217, 217, 217));
        txtuts.setBorder(null);
        txtuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtutsActionPerformed(evt);
            }
        });
        getContentPane().add(txtuts, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 250, 30));

        txtuas.setBackground(new java.awt.Color(217, 217, 217));
        txtuas.setBorder(null);
        txtuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuasActionPerformed(evt);
            }
        });
        getContentPane().add(txtuas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 250, 30));

        outnim.setBackground(new java.awt.Color(217, 217, 217));
        outnim.setBorder(null);
        outnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outnimActionPerformed(evt);
            }
        });
        getContentPane().add(outnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 270, 30));

        outnama.setBackground(new java.awt.Color(217, 217, 217));
        outnama.setBorder(null);
        outnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outnamaActionPerformed(evt);
            }
        });
        getContentPane().add(outnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 280, 30));

        outakhir.setBackground(new java.awt.Color(217, 217, 217));
        outakhir.setBorder(null);
        getContentPane().add(outakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 260, 30));

        outgrade.setBackground(new java.awt.Color(217, 217, 217));
        outgrade.setBorder(null);
        outgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outgradeActionPerformed(evt);
            }
        });
        getContentPane().add(outgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 260, 30));

        outket.setBackground(new java.awt.Color(217, 217, 217));
        outket.setBorder(null);
        outket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outketActionPerformed(evt);
            }
        });
        getContentPane().add(outket, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 230, 80));

        btnsubmit.setContentAreaFilled(false);
        btnsubmit.setBackground(new java.awt.Color(217, 217, 217));
        btnsubmit.setBorder(null);
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 60, 40));

        btndownload.setContentAreaFilled(false);
        btndownload.setBackground(new java.awt.Color(217, 217, 217));
        btndownload.setBorder(null);
        btndownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndownloadActionPerformed(evt);
            }
        });
        getContentPane().add(btndownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 570, 70, 40));

        btnclear.setContentAreaFilled(false);
        btnclear.setBackground(new java.awt.Color(153, 153, 153));
        btnclear.setBorder(null);
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 640, 110, 50));

        btnexit.setContentAreaFilled(false);
        btnexit.setBackground(new java.awt.Color(153, 153, 153));
        btnexit.setBorder(null);
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 640, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Untitled (4).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1130, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnimActionPerformed

    private void txtutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtutsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtutsActionPerformed

    private void outgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outgradeActionPerformed

    private void outketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outketActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        if (txtnim.getText().equals("") || txtnama.getText().equals("") ||
                txtabsen.getText().equals("") || txttugas.getText().equals("") ||
                txtuts.getText().equals("") || txtuas.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap isi semua kolom!");
            return; // Hentikan eksekusi jika ada yang kosong
        }
        if (!txtnim.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "NIM hanya boleh berisi angka!");
            return; // Hentikan eksekusi jika NIM tidak berisi angka
        }
        if (!txtnama.getText().matches("^[a-zA-Z ]+$")) {
            JOptionPane.showMessageDialog(null, "Nama hanya boleh mengandung huruf!");
            return; // Hentikan eksekusi jika nama mengandung angka atau karakter khusus
        }
        if (!txtabsen.getText().matches("\\d+") ||
                !txttugas.getText().matches("\\d+") ||
                !txtuts.getText().matches("\\d+") ||
                !txtuas.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Nilai harus berisi angka!");
            return; // Hentikan eksekusi jika ada yang tidak berisi angka
        }
        String nim1 = txtnim.getText();
        String nama1 = txtnama.getText();
        String absen1 = txtabsen.getText();
        String tugas1 = txttugas.getText();
        String uts1 = txtuts.getText();
        String uas1 = txtuas.getText();
        
        long nim = Long.parseLong(txtnim.getText());
        int absen = Integer.parseInt(txtabsen.getText());
        int tugas = Integer.parseInt(txttugas.getText());
        int uts = Integer.parseInt(txtuts.getText());
        int uas = Integer.parseInt(txtuas.getText());
        
        String grade = null;
        String ket = null;
        
        if (absen >= 0 && absen <= 100 && tugas >= 0 && tugas <= 100 && uts >= 0 && uts <= 100
                && uas >= 0 && uas <= 100) {
            double nilai_akhir = ((absen * 0.1) + (tugas * 0.25) + (uts * 0.3) + (uas * 0.35));
            if (nilai_akhir >= 90 && nilai_akhir <= 100) {
                grade = "A";
                ket = "Anda Lulus";
            } else if (nilai_akhir >= 80 && nilai_akhir <= 89) {
                grade = "B";
                ket = "Anda Lulus";
            } else if (nilai_akhir >= 70 && nilai_akhir <= 79) {
                grade = "C";
                ket = "Anda Lulus";
            } else {
                grade = "D";
                ket = "Anda Tidak Lulus";
            }
            outnim.setText(nim1);
            outnama.setText(nama1);
            outakhir.setText(String.valueOf(nilai_akhir));
            outgrade.setText(grade);
            outket.setText(ket);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nilai tidak diantara 0-100");
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txttugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttugasActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        int replay = JOptionPane.showConfirmDialog(null,
                "Yakin mau keluar","Konfirmasi keluar aplikasi",JOptionPane.YES_NO_OPTION);
        if (replay == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtnim.setText("");
        txtnama.setText("");
        txtabsen.setText("");
        txttugas.setText("");
        txtuts.setText("");
        txtuas.setText("");
        outnim.setText("");
        outnama.setText("");
        outakhir.setText("");
        outgrade.setText("");
        outket.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btndownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndownloadActionPerformed
        // TODO add your handling code here:
        if (isOutputNotEmpty()) {
            try {
                BufferedWriter obj = new BufferedWriter(new FileWriter("Hasil.txt"));
                String hasil = "NIM : " + outnim.getText() + '\n' + "NAMA : " + outnama.getText() + '\n' +
                        "NILAI AKHIR : " + outakhir.getText() + '\n' + "GRADE : " + outgrade.getText() + '\n' +
                        "KETERANGAN : " + outket.getText();
                obj.write((hasil));
                JOptionPane.showMessageDialog(null, "Berhasil disimpan");
                obj.close();
            } catch (Exception e) {
                System.out.println("Eror : " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tidak dapat menyimpan. Pastikan semua output diisi.");
        }
    
        
    }//GEN-LAST:event_btndownloadActionPerformed

    private void txtuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuasActionPerformed

    private void outnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outnimActionPerformed

    private void outnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outnamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndownload;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField outakhir;
    private javax.swing.JTextField outgrade;
    private javax.swing.JTextField outket;
    private javax.swing.JTextField outnama;
    private javax.swing.JTextField outnim;
    private javax.swing.JTextField txtabsen;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnim;
    private javax.swing.JTextField txttugas;
    private javax.swing.JTextField txtuas;
    private javax.swing.JTextField txtuts;
    // End of variables declaration//GEN-END:variables

    private boolean isOutputNotEmpty() {
        return !outnim.getText().isEmpty() &&
                !outnama.getText().isEmpty() &&
                !outakhir.getText().isEmpty() &&
                !outgrade.getText().isEmpty() &&
                !outket.getText().isEmpty();
    }
}
